#TestDB
#TRUNCATE

import mysql.connector
import random
import string

db=mysql.connector.connect(
    host = 'localhost',
    user = 'root',
    passwd = 'root',
    database = 'TestDB'
)

myCursor = db.cursor()

#myCursor.execute("CREATE TABLE Vault(userName varchar(50) NOT NULL, pass varchar(50)NOT NULL, recoveryKey varchar(50))")

'''
Take arguments for 'userName', 'pass' then adds it to Table
Recovery key is generated by Random module
'''
def add(uname, password):
    key = ''
    for x in range(7):
        key += random.choice(string.ascii_letters)
    myCursor.execute(f"INSERT INTO Vault(userName, pass, recoveryKey) VALUES('{uname}','{password}','{key}')")
    db.commit()

'''
1. In check(), the defalut value is false i.e. it is considered by default that 
   there is no similar username
2. First cursor selects the row with given value as username
3. Then a for loop is run to go through value; if a value is found the if function 
   then changes the value of 'value' to False.
4. At last the value of 'value' is returned
5.If name is there then True is returned and vice-versa
'''
def check(uname):
    myCursor.execute(f"SELECT * FROM VAULT WHERE userName = '{uname}'")
    value = False
    for i in myCursor:
        print(i)
        if i != '':
            value = True
            break
    return value

#add('Rashmi', 'moti')

myCursor.execute("SELECT * FROM Vault")
for i in myCursor:
    print(i)